target 'BeautyContestv1' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
pod 'Koloda', '~> 4.3.0'
pod 'SnapKit', '~> 4.0'
# Pods for BeautyContest

end
